### ISSUE TITLE
Error while trying to seal a secret if --disable-load-secrets activated

### ISSUE THREAD

**Issue by rprin** [ricoberger/sealed-secrets-web#7]
Hi,
first of all thank you for this project :)  

With release 2.1.4 and 2.1.5 if I hide the "secrets" menu item with the arg "--disable-load-secrets" I get an error if I try to seal the secret you provide as an example (or any other secret). 
If I remove the arg  "--disable-load-secrets", everything works fine.

![screenshot 2020-01-31 à 08 36 56](https://user-images.githubusercontent.com/1118715/73520863-e756ba00-4404-11ea-9977-bc174f40c44a.png)

Thank you

**Comment by ricoberger** [comment]
Hi and sorry for the circumstances. I've found the bug: The problem is that I pass all arguments from `sealedsecretsweb` to `kubeseal` and the `--disable-load-secrets` is not defined for `kubeseal`.

To avoid this in the future I will change this handling. So that there are only four arguments for `sealedsecretsweb`:

- `disable-load-secrets`: Disable the loading of existing secrets
- `format`: Set the in and output format (`json` or `yaml`)
- `kubeseal-args`: Arguments which will be passed to `kubeseal` (`--kubeseal-args '--controller-name sealed-secrets --format yaml'`)
- `version`: Print version information

I will also update the used version of `kubeseal`. Hopefully I get this done over the weekend.

**Comment by ricoberger** [comment]
I published a new release: [2.2.0](https://github.com/ricoberger/sealed-secrets-web/releases/tag/2.2.0).

Which changes the flag handling and should fix the error. I also updated kubeseal to [v0.9.7](https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.9.7).

If you have any issues, feel free to open a new issue or to reopen this one.

**Comment by solune** [comment]
Hi,
I just try with this config:
```yaml
sealed-secrets-web:
  image:
    args:
      - --kubeseal-arguments="--controller-name admin-sealed-secrets --controller-namespace admin"
      - --disable-load-secrets
```
And I steel have error 400. How can I generate log to help you ?
I just have 
```
Starting "Sealed Secrets" Web Interface (version=2.2.0, branch=HEAD, revision=8da77ee5d0518f0447e6c118f8
125b7691887cc0)
Build context (go=go1.12.16, user=runner, date=20200201-20:07:18)
Listening on :8080
```

**Comment by ricoberger** [comment]
Hi, the problem is that your using double quotes in the `kubeseal-arguments` flag. Can you try the following please:

```diff
sealed-secrets-web:
  image:
    args:
-      - --kubeseal-arguments="--controller-name admin-sealed-secrets --controller-namespace admin"
+      - --kubeseal-arguments=--controller-name admin-sealed-secrets --controller-namespace admin
      - --disable-load-secrets
```

**Comment by rprin** [comment]
Works well with this configuration (without double-quotes). Many thanks for your reactivity !
